// Auto-generated by scripts/extract_seed.py from data/Workout_Tracker_V1.xlsx
// Used only the first time the app runs, to pre-fill localStorage.
const SEED_DATA = {
  "categories": [
    "Legs",
    "Arms",
    "Chest",
    "Back",
    "Shoulders",
    "Core",
    "Cardio"
  ],
  "exercises": [
    {
      "id": "legs__hack-squat-upright",
      "name": "Hack Squat (Upright)",
      "category": "Legs"
    },
    {
      "id": "legs__seated-leg-curl",
      "name": "Seated Leg Curl",
      "category": "Legs"
    },
    {
      "id": "legs__hip-abductor-internal",
      "name": "Hip Abductor (Internal)",
      "category": "Legs"
    },
    {
      "id": "legs__hip-abductor-external",
      "name": "Hip Abductor (External)",
      "category": "Legs"
    },
    {
      "id": "legs__hip-thrust-machine",
      "name": "Hip Thrust Machine",
      "category": "Legs"
    },
    {
      "id": "legs__dumbell-split-squat",
      "name": "Dumbell Split Squat",
      "category": "Legs"
    },
    {
      "id": "arms__curls",
      "name": "Curls",
      "category": "Arms"
    },
    {
      "id": "arms__cable-curl-looking-away",
      "name": "Cable Curl (Looking Away)",
      "category": "Arms"
    },
    {
      "id": "arms__push-down-machine",
      "name": "Push Down Machine",
      "category": "Arms"
    },
    {
      "id": "arms__single-arm-push-down-matrix",
      "name": "Single Arm Push Down (Matrix)",
      "category": "Arms"
    },
    {
      "id": "arms__push-down-regular",
      "name": "Push Down (Regular)",
      "category": "Arms"
    },
    {
      "id": "chest__dumbbell-press-flat",
      "name": "Dumbbell Press (Flat)",
      "category": "Chest"
    },
    {
      "id": "chest__iso-lat-bench",
      "name": "Iso Lat Bench",
      "category": "Chest"
    },
    {
      "id": "chest__incline-smith-machine",
      "name": "Incline Smith Machine",
      "category": "Chest"
    },
    {
      "id": "chest__chest-press-machine",
      "name": "Chest Press Machine",
      "category": "Chest"
    },
    {
      "id": "chest__bench",
      "name": "Bench",
      "category": "Chest"
    },
    {
      "id": "chest__chest-fly",
      "name": "Chest Fly",
      "category": "Chest"
    },
    {
      "id": "chest__dumbbell-press-incline",
      "name": "Dumbbell Press (Incline)",
      "category": "Chest"
    },
    {
      "id": "chest__cable-chest-press-incline",
      "name": "Cable Chest Press (Incline)",
      "category": "Chest"
    },
    {
      "id": "back__t-bar-chest-supported-row",
      "name": "T-Bar Chest Supported Row",
      "category": "Back"
    },
    {
      "id": "back__lat-pulldown-machine",
      "name": "Lat Pulldown Machine",
      "category": "Back"
    },
    {
      "id": "back__pullups",
      "name": "Pullups",
      "category": "Back"
    },
    {
      "id": "back__iso-lat-row-hammer-machine",
      "name": "Iso Lat Row (Hammer Machine)",
      "category": "Back"
    },
    {
      "id": "back__lat-pulldown-hammer-strength-machine",
      "name": "Lat Pulldown (Hammer Strength Machine)",
      "category": "Back"
    },
    {
      "id": "shoulders__dumbell-lat-raise",
      "name": "Dumbell Lat Raise",
      "category": "Shoulders"
    },
    {
      "id": "core__cable-crunch",
      "name": "Cable Crunch",
      "category": "Core"
    },
    {
      "id": "cardio__assault-bike",
      "name": "Assault Bike",
      "category": "Cardio"
    },
    {
      "id": "cardio__stairmaster",
      "name": "Stairmaster",
      "category": "Cardio"
    }
  ],
  "logs": [
    {
      "id": 1,
      "date": "2026-02-28",
      "exerciseId": "legs__hack-squat-upright",
      "set": 1,
      "weight": 105.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 2,
      "date": "2026-02-28",
      "exerciseId": "legs__hack-squat-upright",
      "set": 2,
      "weight": 115.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 3,
      "date": "2026-02-28",
      "exerciseId": "legs__hack-squat-upright",
      "set": 3,
      "weight": 155.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 4,
      "date": "2026-03-05",
      "exerciseId": "legs__hack-squat-upright",
      "set": 1,
      "weight": 155.0,
      "reps": 11.0,
      "comment": null
    },
    {
      "id": 5,
      "date": "2026-03-05",
      "exerciseId": "legs__hack-squat-upright",
      "set": 2,
      "weight": 175.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 6,
      "date": "2026-03-05",
      "exerciseId": "legs__hack-squat-upright",
      "set": 3,
      "weight": 185.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 7,
      "date": "2026-03-05",
      "exerciseId": "legs__hack-squat-upright",
      "set": 4,
      "weight": 195.0,
      "reps": 3.0,
      "comment": null
    },
    {
      "id": 8,
      "date": "2026-03-05",
      "exerciseId": "legs__hip-abductor-external",
      "set": 1,
      "weight": 110.0,
      "reps": 23.0,
      "comment": null
    },
    {
      "id": 9,
      "date": "2026-03-05",
      "exerciseId": "legs__hip-abductor-external",
      "set": 2,
      "weight": 130.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 10,
      "date": "2026-03-05",
      "exerciseId": "legs__hip-abductor-external",
      "set": 3,
      "weight": 140.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 11,
      "date": "2026-03-05",
      "exerciseId": "legs__hip-abductor-internal",
      "set": 1,
      "weight": 110.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 12,
      "date": "2026-03-05",
      "exerciseId": "legs__seated-leg-curl",
      "set": 1,
      "weight": 30.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 13,
      "date": "2026-03-05",
      "exerciseId": "legs__seated-leg-curl",
      "set": 2,
      "weight": 40.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 14,
      "date": "2026-03-05",
      "exerciseId": "legs__seated-leg-curl",
      "set": 3,
      "weight": 50.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 15,
      "date": "2026-03-20",
      "exerciseId": "legs__hack-squat-upright",
      "set": 1,
      "weight": 155.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 16,
      "date": "2026-03-20",
      "exerciseId": "legs__hack-squat-upright",
      "set": 2,
      "weight": 175.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 17,
      "date": "2026-03-20",
      "exerciseId": "legs__hack-squat-upright",
      "set": 3,
      "weight": 195.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 18,
      "date": "2026-03-20",
      "exerciseId": "legs__hack-squat-upright",
      "set": 4,
      "weight": 155.0,
      "reps": 4.0,
      "comment": null
    },
    {
      "id": 19,
      "date": "2026-03-20",
      "exerciseId": "legs__seated-leg-curl",
      "set": 1,
      "weight": 30.0,
      "reps": 15.0,
      "comment": null
    },
    {
      "id": 20,
      "date": "2026-03-20",
      "exerciseId": "legs__seated-leg-curl",
      "set": 2,
      "weight": 60.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 21,
      "date": "2026-03-20",
      "exerciseId": "legs__seated-leg-curl",
      "set": 3,
      "weight": 60.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 22,
      "date": "2026-03-20",
      "exerciseId": "legs__seated-leg-curl",
      "set": 4,
      "weight": 30.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 23,
      "date": "2026-04-13",
      "exerciseId": "legs__hack-squat-upright",
      "set": 1,
      "weight": 175.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 24,
      "date": "2026-04-13",
      "exerciseId": "legs__hack-squat-upright",
      "set": 2,
      "weight": 195.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 25,
      "date": "2026-04-13",
      "exerciseId": "legs__hack-squat-upright",
      "set": 3,
      "weight": 215.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 26,
      "date": "2026-04-16",
      "exerciseId": "legs__seated-leg-curl",
      "set": 1,
      "weight": 30.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 27,
      "date": "2026-04-16",
      "exerciseId": "legs__seated-leg-curl",
      "set": 2,
      "weight": 40.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 28,
      "date": "2026-04-16",
      "exerciseId": "legs__seated-leg-curl",
      "set": 3,
      "weight": 50.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 29,
      "date": "2026-04-16",
      "exerciseId": "legs__seated-leg-curl",
      "set": 4,
      "weight": 60.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 30,
      "date": "2026-04-22",
      "exerciseId": "legs__hack-squat-upright",
      "set": 2,
      "weight": 195.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 31,
      "date": "2026-04-22",
      "exerciseId": "legs__hack-squat-upright",
      "set": 3,
      "weight": 215.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 32,
      "date": "2026-04-22",
      "exerciseId": "legs__hack-squat-upright",
      "set": 4,
      "weight": 215.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 33,
      "date": "2026-04-22",
      "exerciseId": "legs__hip-abductor-external",
      "set": 1,
      "weight": 140.0,
      "reps": 18.0,
      "comment": null
    },
    {
      "id": 34,
      "date": "2026-04-22",
      "exerciseId": "legs__hip-abductor-external",
      "set": 2,
      "weight": 140.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 35,
      "date": "2026-02-06",
      "exerciseId": "arms__single-arm-push-down-matrix",
      "set": 1,
      "weight": 12.5,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 36,
      "date": "2026-02-06",
      "exerciseId": "arms__single-arm-push-down-matrix",
      "set": 2,
      "weight": 12.5,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 37,
      "date": "2026-02-20",
      "exerciseId": "arms__push-down-regular",
      "set": 1,
      "weight": 40.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 38,
      "date": "2026-02-20",
      "exerciseId": "arms__push-down-regular",
      "set": 2,
      "weight": 35.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 39,
      "date": "2026-03-01",
      "exerciseId": "arms__curls",
      "set": 1,
      "weight": 35.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 40,
      "date": "2026-03-01",
      "exerciseId": "arms__curls",
      "set": 2,
      "weight": 30.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 41,
      "date": "2026-03-01",
      "exerciseId": "arms__push-down-machine",
      "set": 1,
      "weight": 160.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 42,
      "date": "2026-03-01",
      "exerciseId": "arms__push-down-machine",
      "set": 2,
      "weight": 160.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 43,
      "date": "2026-03-01",
      "exerciseId": "arms__push-down-machine",
      "set": 3,
      "weight": 160.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 44,
      "date": "2026-03-14",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 1,
      "weight": 12.5,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 45,
      "date": "2026-03-14",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 2,
      "weight": 17.5,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 46,
      "date": "2026-03-14",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 3,
      "weight": 17.5,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 47,
      "date": "2026-03-14",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 4,
      "weight": 22.5,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 48,
      "date": "2026-03-14",
      "exerciseId": "arms__push-down-machine",
      "set": 1,
      "weight": 160.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 49,
      "date": "2026-03-14",
      "exerciseId": "arms__push-down-machine",
      "set": 2,
      "weight": 175.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 50,
      "date": "2026-03-14",
      "exerciseId": "arms__push-down-machine",
      "set": 3,
      "weight": 190.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 51,
      "date": "2026-03-14",
      "exerciseId": "arms__push-down-machine",
      "set": 4,
      "weight": 190.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 52,
      "date": "2026-03-14",
      "exerciseId": "arms__push-down-machine",
      "set": 5,
      "weight": 205.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 53,
      "date": "2026-03-21",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 1,
      "weight": 20.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 54,
      "date": "2026-03-21",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 2,
      "weight": 20.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 55,
      "date": "2026-03-21",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 3,
      "weight": 15.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 56,
      "date": "2026-03-21",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 4,
      "weight": 15.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 57,
      "date": "2026-03-21",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 5,
      "weight": 15.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 58,
      "date": "2026-03-21",
      "exerciseId": "arms__push-down-regular",
      "set": 1,
      "weight": 42.0,
      "reps": 9.0,
      "comment": null
    },
    {
      "id": 59,
      "date": "2026-03-21",
      "exerciseId": "arms__push-down-regular",
      "set": 2,
      "weight": 37.5,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 60,
      "date": "2026-03-21",
      "exerciseId": "arms__push-down-regular",
      "set": 3,
      "weight": 32.5,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 61,
      "date": "2026-03-21",
      "exerciseId": "arms__push-down-machine",
      "set": 1,
      "weight": 190.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 62,
      "date": "2026-03-21",
      "exerciseId": "arms__push-down-machine",
      "set": 2,
      "weight": 205.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 63,
      "date": "2026-03-21",
      "exerciseId": "arms__push-down-machine",
      "set": 3,
      "weight": 205.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 64,
      "date": "2026-03-24",
      "exerciseId": "arms__curls",
      "set": 1,
      "weight": 40.0,
      "reps": 5.0,
      "comment": null
    },
    {
      "id": 65,
      "date": "2026-03-24",
      "exerciseId": "arms__curls",
      "set": 2,
      "weight": 35.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 66,
      "date": "2026-04-01",
      "exerciseId": "arms__curls",
      "set": 1,
      "weight": 40.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 67,
      "date": "2026-04-01",
      "exerciseId": "arms__curls",
      "set": 2,
      "weight": 35.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 68,
      "date": "2026-04-03",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 1,
      "weight": 22.5,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 69,
      "date": "2026-04-03",
      "exerciseId": "arms__cable-curl-looking-away",
      "set": 2,
      "weight": 22.5,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 70,
      "date": "2026-04-03",
      "exerciseId": "arms__curls",
      "set": 1,
      "weight": 40.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 71,
      "date": "2026-04-03",
      "exerciseId": "arms__single-arm-push-down-matrix",
      "set": 1,
      "weight": 27.5,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 72,
      "date": "2026-04-03",
      "exerciseId": "arms__single-arm-push-down-matrix",
      "set": 2,
      "weight": 17.5,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 73,
      "date": "2026-04-14",
      "exerciseId": "arms__push-down-regular",
      "set": 1,
      "weight": 37.5,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 74,
      "date": "2026-04-14",
      "exerciseId": "arms__push-down-regular",
      "set": 2,
      "weight": 37.5,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 75,
      "date": "2026-05-13",
      "exerciseId": "arms__single-arm-push-down-matrix",
      "set": 1,
      "weight": 17.5,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 76,
      "date": "2026-05-13",
      "exerciseId": "arms__single-arm-push-down-matrix",
      "set": 2,
      "weight": 22.5,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 77,
      "date": "2026-05-14",
      "exerciseId": "arms__push-down-machine",
      "set": 1,
      "weight": 205.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 78,
      "date": "2026-05-14",
      "exerciseId": "arms__push-down-machine",
      "set": 2,
      "weight": 220.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 79,
      "date": "2026-05-14",
      "exerciseId": "arms__push-down-machine",
      "set": 3,
      "weight": 220.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 80,
      "date": "2026-02-15",
      "exerciseId": "chest__bench",
      "set": 1,
      "weight": 135.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 81,
      "date": "2026-02-15",
      "exerciseId": "chest__bench",
      "set": 2,
      "weight": 145.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 82,
      "date": "2026-02-20",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 83,
      "date": "2026-02-20",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 35.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 84,
      "date": "2026-02-28",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 80.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 85,
      "date": "2026-02-28",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 100.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 86,
      "date": "2026-02-28",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 100.0,
      "reps": 9.0,
      "comment": null
    },
    {
      "id": 87,
      "date": "2026-02-28",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 35.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 88,
      "date": "2026-02-28",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 45.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 89,
      "date": "2026-02-28",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 45.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 90,
      "date": "2026-02-28",
      "exerciseId": "chest__incline-smith-machine",
      "set": 4,
      "weight": 45.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 91,
      "date": "2026-02-28",
      "exerciseId": "chest__incline-smith-machine",
      "set": 5,
      "weight": 45.0,
      "reps": 4.0,
      "comment": null
    },
    {
      "id": 92,
      "date": "2026-03-02",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 100.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 93,
      "date": "2026-03-02",
      "exerciseId": "chest__chest-press-machine",
      "set": 1,
      "weight": 80.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 94,
      "date": "2026-03-02",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 95,
      "date": "2026-03-02",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 45.0,
      "reps": 9.0,
      "comment": null
    },
    {
      "id": 96,
      "date": "2026-03-02",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 45.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 97,
      "date": "2026-03-02",
      "exerciseId": "chest__incline-smith-machine",
      "set": 4,
      "weight": 45.0,
      "reps": 5.0,
      "comment": null
    },
    {
      "id": 98,
      "date": "2026-03-09",
      "exerciseId": "chest__bench",
      "set": 1,
      "weight": 145.0,
      "reps": 15.0,
      "comment": null
    },
    {
      "id": 99,
      "date": "2026-03-09",
      "exerciseId": "chest__bench",
      "set": 2,
      "weight": 145.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 100,
      "date": "2026-03-09",
      "exerciseId": "chest__bench",
      "set": 3,
      "weight": 145.0,
      "reps": 11.0,
      "comment": null
    },
    {
      "id": 101,
      "date": "2026-03-09",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 100.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 102,
      "date": "2026-03-09",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 120.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 103,
      "date": "2026-03-09",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 120.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 104,
      "date": "2026-03-09",
      "exerciseId": "chest__chest-fly",
      "set": 4,
      "weight": 100.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 105,
      "date": "2026-03-15",
      "exerciseId": "chest__bench",
      "set": 1,
      "weight": 145.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 106,
      "date": "2026-03-15",
      "exerciseId": "chest__bench",
      "set": 2,
      "weight": 155.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 107,
      "date": "2026-03-15",
      "exerciseId": "chest__bench",
      "set": 3,
      "weight": 165.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 108,
      "date": "2026-03-15",
      "exerciseId": "chest__chest-press-machine",
      "set": 1,
      "weight": 110.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 109,
      "date": "2026-03-15",
      "exerciseId": "chest__chest-press-machine",
      "set": 2,
      "weight": 110.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 110,
      "date": "2026-03-15",
      "exerciseId": "chest__chest-press-machine",
      "set": 3,
      "weight": 120.0,
      "reps": 5.0,
      "comment": null
    },
    {
      "id": 111,
      "date": "2026-03-15",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 1,
      "weight": 50.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 112,
      "date": "2026-03-15",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 2,
      "weight": 50.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 113,
      "date": "2026-03-15",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 3,
      "weight": 50.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 114,
      "date": "2026-03-15",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 115,
      "date": "2026-03-15",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 45.0,
      "reps": 13.0,
      "comment": null
    },
    {
      "id": 116,
      "date": "2026-03-15",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 55.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 117,
      "date": "2026-03-22",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 35.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 118,
      "date": "2026-03-22",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 45.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 119,
      "date": "2026-03-22",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 55.0,
      "reps": 9.0,
      "comment": null
    },
    {
      "id": 120,
      "date": "2026-03-23",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 120.0,
      "reps": 13.0,
      "comment": null
    },
    {
      "id": 121,
      "date": "2026-03-24",
      "exerciseId": "chest__bench",
      "set": 1,
      "weight": 145.0,
      "reps": 15.0,
      "comment": null
    },
    {
      "id": 122,
      "date": "2026-03-24",
      "exerciseId": "chest__bench",
      "set": 2,
      "weight": 155.0,
      "reps": 9.0,
      "comment": null
    },
    {
      "id": 123,
      "date": "2026-03-24",
      "exerciseId": "chest__bench",
      "set": 3,
      "weight": 165.0,
      "reps": 2.0,
      "comment": null
    },
    {
      "id": 124,
      "date": "2026-03-24",
      "exerciseId": "chest__chest-press-machine",
      "set": 1,
      "weight": 110.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 125,
      "date": "2026-03-24",
      "exerciseId": "chest__chest-press-machine",
      "set": 2,
      "weight": 120.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 126,
      "date": "2026-03-24",
      "exerciseId": "chest__chest-press-machine",
      "set": 3,
      "weight": 120.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 127,
      "date": "2026-04-01",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 140.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 128,
      "date": "2026-04-01",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 120.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 129,
      "date": "2026-04-01",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 120.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 130,
      "date": "2026-04-01",
      "exerciseId": "chest__chest-fly",
      "set": 4,
      "weight": 100.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 131,
      "date": "2026-04-06",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 120.0,
      "reps": 17.0,
      "comment": null
    },
    {
      "id": 132,
      "date": "2026-04-06",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 1,
      "weight": 55.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 133,
      "date": "2026-04-06",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 2,
      "weight": 55.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 134,
      "date": "2026-04-06",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 3,
      "weight": 55.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 135,
      "date": "2026-04-06",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 35.0,
      "reps": 5.0,
      "comment": null
    },
    {
      "id": 136,
      "date": "2026-04-06",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 45.0,
      "reps": 15.0,
      "comment": null
    },
    {
      "id": 137,
      "date": "2026-04-06",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 55.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 138,
      "date": "2026-04-06",
      "exerciseId": "chest__incline-smith-machine",
      "set": 4,
      "weight": 65.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 139,
      "date": "2026-04-07",
      "exerciseId": "chest__bench",
      "set": 1,
      "weight": 165.0,
      "reps": 2.0,
      "comment": null
    },
    {
      "id": 140,
      "date": "2026-04-07",
      "exerciseId": "chest__bench",
      "set": 2,
      "weight": 185.0,
      "reps": 2.0,
      "comment": null
    },
    {
      "id": 141,
      "date": "2026-04-07",
      "exerciseId": "chest__bench",
      "set": 3,
      "weight": 195.0,
      "reps": 2.0,
      "comment": null
    },
    {
      "id": 142,
      "date": "2026-04-14",
      "exerciseId": "chest__dumbbell-press-flat",
      "set": 1,
      "weight": 55.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 143,
      "date": "2026-04-14",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 55.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 144,
      "date": "2026-04-20",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 120.0,
      "reps": 20.0,
      "comment": null
    },
    {
      "id": 145,
      "date": "2026-04-20",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 140.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 146,
      "date": "2026-04-20",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 140.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 147,
      "date": "2026-04-20",
      "exerciseId": "chest__chest-press-machine",
      "set": 1,
      "weight": 120.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 148,
      "date": "2026-04-20",
      "exerciseId": "chest__chest-press-machine",
      "set": 2,
      "weight": 130.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 149,
      "date": "2026-04-20",
      "exerciseId": "chest__chest-press-machine",
      "set": 3,
      "weight": 140.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 150,
      "date": "2026-04-20",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 60.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 151,
      "date": "2026-04-20",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 2,
      "weight": 60.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 152,
      "date": "2026-04-20",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 3,
      "weight": 60.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 153,
      "date": "2026-04-26",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 120.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 154,
      "date": "2026-04-26",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 160.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 155,
      "date": "2026-04-26",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 160.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 156,
      "date": "2026-04-26",
      "exerciseId": "chest__chest-fly",
      "set": 4,
      "weight": 140.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 157,
      "date": "2026-04-28",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 65.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 158,
      "date": "2026-04-28",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 2,
      "weight": 65.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 159,
      "date": "2026-04-28",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 3,
      "weight": 65.0,
      "reps": 4.0,
      "comment": null
    },
    {
      "id": 160,
      "date": "2026-05-02",
      "exerciseId": "chest__bench",
      "set": 1,
      "weight": 195.0,
      "reps": 3.0,
      "comment": null
    },
    {
      "id": 161,
      "date": "2026-05-02",
      "exerciseId": "chest__iso-lat-bench",
      "set": 1,
      "weight": 45.0,
      "reps": 16.0,
      "comment": null
    },
    {
      "id": 162,
      "date": "2026-05-02",
      "exerciseId": "chest__iso-lat-bench",
      "set": 2,
      "weight": 55.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 163,
      "date": "2026-05-03",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 65.0,
      "reps": 11.0,
      "comment": null
    },
    {
      "id": 164,
      "date": "2026-05-10",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 160.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 165,
      "date": "2026-05-10",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 180.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 166,
      "date": "2026-05-10",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 160.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 167,
      "date": "2026-05-12",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 65.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 168,
      "date": "2026-05-12",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 2,
      "weight": 65.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 169,
      "date": "2026-05-12",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 3,
      "weight": 65.0,
      "reps": 4.0,
      "comment": null
    },
    {
      "id": 170,
      "date": "2026-05-17",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 171,
      "date": "2026-05-17",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 55.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 172,
      "date": "2026-05-17",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 65.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 173,
      "date": "2026-05-18",
      "exerciseId": "chest__iso-lat-bench",
      "set": 1,
      "weight": 70.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 174,
      "date": "2026-05-20",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 140.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 175,
      "date": "2026-05-20",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 160.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 176,
      "date": "2026-05-25",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 177,
      "date": "2026-05-25",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 65.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 178,
      "date": "2026-05-25",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 70.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 179,
      "date": "2026-05-25",
      "exerciseId": "chest__incline-smith-machine",
      "set": 4,
      "weight": 65.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 180,
      "date": "2026-06-09",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 60.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 181,
      "date": "2026-06-09",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 2,
      "weight": 65.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 182,
      "date": "2026-06-09",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 3,
      "weight": 70.0,
      "reps": 5.0,
      "comment": null
    },
    {
      "id": 183,
      "date": "2026-06-25",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 1,
      "weight": 65.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 184,
      "date": "2026-06-25",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 2,
      "weight": 65.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 185,
      "date": "2026-06-25",
      "exerciseId": "chest__dumbbell-press-incline",
      "set": 3,
      "weight": 65.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 186,
      "date": "2026-07-27",
      "exerciseId": "chest__incline-smith-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 187,
      "date": "2026-07-27",
      "exerciseId": "chest__incline-smith-machine",
      "set": 2,
      "weight": 55.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 188,
      "date": "2026-07-27",
      "exerciseId": "chest__incline-smith-machine",
      "set": 3,
      "weight": 65.0,
      "reps": 4.0,
      "comment": null
    },
    {
      "id": 189,
      "date": "2026-07-27",
      "exerciseId": "chest__incline-smith-machine",
      "set": 4,
      "weight": 45.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 190,
      "date": "2026-07-27",
      "exerciseId": "chest__chest-fly",
      "set": 1,
      "weight": 180.0,
      "reps": 9.0,
      "comment": null
    },
    {
      "id": 191,
      "date": "2026-07-27",
      "exerciseId": "chest__chest-fly",
      "set": 2,
      "weight": 180.0,
      "reps": 4.0,
      "comment": null
    },
    {
      "id": 192,
      "date": "2026-07-27",
      "exerciseId": "chest__chest-fly",
      "set": 3,
      "weight": 160.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 193,
      "date": "2026-03-12",
      "exerciseId": "back__pullups",
      "set": 1,
      "weight": null,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 194,
      "date": "2026-03-12",
      "exerciseId": "back__pullups",
      "set": 2,
      "weight": null,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 195,
      "date": "2026-03-12",
      "exerciseId": "back__pullups",
      "set": 3,
      "weight": null,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 196,
      "date": "2026-03-12",
      "exerciseId": "back__pullups",
      "set": 4,
      "weight": null,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 197,
      "date": "2026-03-16",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 1,
      "weight": 90.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 198,
      "date": "2026-03-16",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 2,
      "weight": 90.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 199,
      "date": "2026-03-16",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 3,
      "weight": 90.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 200,
      "date": "2026-03-23",
      "exerciseId": "back__pullups",
      "set": 1,
      "weight": null,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 201,
      "date": "2026-03-23",
      "exerciseId": "back__pullups",
      "set": 2,
      "weight": null,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 202,
      "date": "2026-03-31",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 203,
      "date": "2026-03-31",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 2,
      "weight": 65.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 204,
      "date": "2026-03-31",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 3,
      "weight": 65.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 205,
      "date": "2026-04-01",
      "exerciseId": "back__pullups",
      "set": 1,
      "weight": null,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 206,
      "date": "2026-04-01",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 1,
      "weight": 45.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 207,
      "date": "2026-04-01",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 2,
      "weight": 90.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 208,
      "date": "2026-04-01",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 3,
      "weight": 90.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 209,
      "date": "2026-04-07",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 1,
      "weight": 70.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 210,
      "date": "2026-04-07",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 2,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 211,
      "date": "2026-04-07",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 3,
      "weight": 45.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 212,
      "date": "2026-04-07",
      "exerciseId": "back__lat-pulldown-machine",
      "set": 1,
      "weight": 120.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 213,
      "date": "2026-04-07",
      "exerciseId": "back__lat-pulldown-machine",
      "set": 2,
      "weight": 100.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 214,
      "date": "2026-04-07",
      "exerciseId": "back__pullups",
      "set": 1,
      "weight": null,
      "reps": 13.0,
      "comment": null
    },
    {
      "id": 215,
      "date": "2026-04-07",
      "exerciseId": "back__pullups",
      "set": 2,
      "weight": null,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 216,
      "date": "2026-04-07",
      "exerciseId": "back__pullups",
      "set": 3,
      "weight": null,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 217,
      "date": "2026-04-30",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 1,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 218,
      "date": "2026-04-30",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 2,
      "weight": 90.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 219,
      "date": "2026-04-30",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 3,
      "weight": 90.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 220,
      "date": "2026-04-30",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 1,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 221,
      "date": "2026-04-30",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 2,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 222,
      "date": "2026-04-30",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 3,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 223,
      "date": "2026-04-30",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 1,
      "weight": 90.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 224,
      "date": "2026-04-30",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 2,
      "weight": 80.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 225,
      "date": "2026-05-18",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 1,
      "weight": 90.0,
      "reps": 7.0,
      "comment": null
    },
    {
      "id": 226,
      "date": "2026-05-18",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 2,
      "weight": 90.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 227,
      "date": "2026-06-08",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 1,
      "weight": 90.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 228,
      "date": "2026-06-08",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 2,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 229,
      "date": "2026-06-08",
      "exerciseId": "back__iso-lat-row-hammer-machine",
      "set": 3,
      "weight": 90.0,
      "reps": 14.0,
      "comment": null
    },
    {
      "id": 230,
      "date": "2026-06-08",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 1,
      "weight": 90.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 231,
      "date": "2026-06-08",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 2,
      "weight": 80.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 232,
      "date": "2026-07-26",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 1,
      "weight": 45.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 233,
      "date": "2026-07-26",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 2,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 234,
      "date": "2026-07-26",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 3,
      "weight": 90.0,
      "reps": 12.0,
      "comment": null
    },
    {
      "id": 235,
      "date": "2026-07-26",
      "exerciseId": "back__lat-pulldown-hammer-strength-machine",
      "set": 4,
      "weight": 70.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 236,
      "date": "2026-07-26",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 1,
      "weight": 90.0,
      "reps": 10.0,
      "comment": null
    },
    {
      "id": 237,
      "date": "2026-07-26",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 2,
      "weight": 90.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 238,
      "date": "2026-07-26",
      "exerciseId": "back__t-bar-chest-supported-row",
      "set": 3,
      "weight": 90.0,
      "reps": 8.0,
      "comment": null
    },
    {
      "id": 239,
      "date": "2026-05-03",
      "exerciseId": "core__cable-crunch",
      "set": 1,
      "weight": 50.0,
      "reps": 6.0,
      "comment": null
    },
    {
      "id": 240,
      "date": "2026-07-27",
      "exerciseId": "cardio__assault-bike",
      "totalTime": 5.0,
      "distance": null,
      "segments": [
        {
          "time": 5.0,
          "zone": "Zone 2"
        }
      ],
      "comment": null
    }
  ]
};
